### ISSUE TITLE
Compiler switches for library dependencies.

### ISSUE THREAD

**Issue by MichaelMackus** [libtcod/libtcod#59] opened 2020-05-05 02:22 UTC
Would you be opposed to adding compiler switches for the various features? Currently, libtcod requires 3 external libs from what I can tell: SDL2, zlib, and pthreads. However, some games might not need all these external dependencies in order to work properly - for example, I'm working on a simple roguelike with the only dependency being the curses library. If I could disable some/all of the above libraries, that would be helpful.

**Comment by MichaelMackus** [comment] 2020-05-05 02:28
Related https://github.com/libtcod/libtcod/issues/25

**Comment by HexDecimal** [comment] 2020-05-05 04:13
I wouldn't have a problem with them.  Specifically `NO_SDL` and `NO_ZLIB` flags and things along those lines.  Threading libraries were linked more for future plans rather than something that's actively used, and they can be optional.

I suspect if you want a small executable right now the easiest way to do it would be to use Conan to build and link static libraries, which will be removed by the linker if they're not used.

**Comment by MichaelMackus** [comment] 2020-05-05 04:18
Ok thanks for the input. I might look into adding this in a separate PR in the future.

Personally, I prefer to do everything in a single Makefile, and haven't actually used Conan before. I will take a look though, that definitely sounds interesting.

**Comment by HexDecimal** [comment] 2020-05-05 04:36
I'm fine with other methods being used.  Conan was just the most obvious example to me.  If Autotools builds static libraries then you could go ahead and use that instead.

Compared to SCons which is a mess and won't build a static library.  I'm just happy that it runs at all.

**Comment by HexDecimal** [comment] 2020-10-29 03:50
Duplicate of #25

**Comment by HexDecimal** [comment] 2022-07-21 17:17
Compile switches for SDL and threads currently exist.  You can switch them in CMake and the recent port on Vcpkg supports them as features.

**Comment by HexDecimal** [comment] 2022-08-24 19:08
Zlib, lodepng, and SDL are now optional and can be disabled with CMake flags or Vcpkg features.

Now it seems like utf8proc is the only non-header-only library left but it's hard to make it optional since there isn't a good standard way to refer to Unicode character data and trying to remove the printing functions would break many things across the entire library.  So I'm going to skip this unless there's another issue raised for it and close this current issue.

**Closed by HexDecimal** 2022-08-24 19:08 UTC
Labels: enhancement

**Comment by HexDecimal** [comment] 2022-09-10 05:46
Now `utf8proc` is optional too.  Removing that disables the printing functions since that code was designed around Unicode.

With Vcpkg, Installing `libtcod[core]` or disabling libtcod's default features will build libtcod with no non-header-only dependencies.  Perfect if you want the pathfinder, noise gen, or FOV features without all the extra stuff libtcod normally requires.
