### ISSUE TITLE
No releases for ARM64.

### ISSUE THREAD

**Issue by SiennaSaito** [libtcod/libtcod#80] opened 2020-12-30 12:08 UTC
I recently switched from an x86 MacBook to an arm64 MacBook - would be cool if there was a release with support for arm64!

**Comment by HexDecimal** [comment] 2020-12-30 14:34
It's mostly down to the availability of the tools to do this with.  I rely pretty hard on open-source-supporting continuous integration services to make releases.  It was pretty tough to get MacOS releases of any architecture, plus I don't have a MacOS to test with locally, and after having issues with TravisCI I now need to recreate the MacOS builds to use GitHub Actions.  It's unlikely that I'll be able to support MacOS x86 architectures again, not that it should matter too much since it's supposed to be deprecated anyway.

MacOS takes the most effort to work with compared to any other platform I've supported.  Because of the above my progress on MacOS support will probably be less than anyone would hope, but more than anyone should expect.  I ultimately blame C for why things are in a terrible state.

At least for now MacOS should be one of the easier platforms to manually compile libtcod on.  There shouldn't be anything actively preventing arm64 support and I suspect any issues which come up should be easy to fix.

Unless someone else will help then I don't really expect arm64 support anytime soon.  That can change if I get lucky with what GitHub Actions can do.  I'm more likely to support arm64 in python-tcod than in libtcod proper.

**Comment by SiennaSaito** [comment] 2020-12-30 21:16
Gotcha! I'll try compiling it by hand and let you know how I go - will submit a PR to update the readme with instructions when I'm done ⭐️

Hopefully there aren't any architecture related issues with SDL!

**Comment by HexDecimal** [comment] 2020-12-30 23:37
The best choice of build tool is probably AutoTools.  I'm not sure if you can get SDL from Brew, or if you'll have to install it manually by following SDL's instructions.  You'll also need zlib.

SCons relies on a prebuilt version of SDL which I'm not certain about the architecture of.  I assume its a fat x86/x86_64 build and won't work.

Conan should be able to build on any architecture.  You'll have to tell it to build any missing packages.

Be sure to tell me if you're having any related issues.

**Comment by SiennaSaito** [comment] 2020-12-31 00:41
PR is up! https://github.com/libtcod/libtcod/pull/81

I'm an iOS dev so the last time I touched any C / C++ build tooling was all the way back in uni - let me know if anything I've done was problematic ⭐ 

Wasn't too sure about the difference between SCons or Autotools so I just went with Scons and it seemed to work but I had to point it to SDL 2.0.14 instead of 2.0.8 in order to get arm64 support on SDL.

**Comment by SiennaSaito** [comment] 2020-12-31 00:47
I'm currently using libtcod as a framework in Xcode for a Swift based Roguelike with MaxGoren's wrappers (https://github.com/maxgoren/swift-TCOD) - there's a lot of moving parts here as we'd usually use Carthage / Cocoapods / SwiftPM to fetch / build / install our dependencies but everything in this space is quite funky to me so I just built and linked everything by hand and it all seems to work. Didn't need to do anything with zlib - I guess MacOS has it included by default or something :S

**Comment by HexDecimal** [comment] 2020-12-31 03:35
I've merged my GitHub Action for MacOS and #81 hasn't caused any regressions with it.

arm64 support seems like a close possibility now.  I wonder if it's possible to make a universal build for x86_64/arm64 like was done previously with x86/x86_64 as you can see here:
https://github.com/libtcod/libtcod/blob/c2294061a4f54b7d0d301f93c47193beed9f92c4/buildsys/scons/SConstruct#L388-L393

I think adding the `-arch arm64 -arch x86_64` flags together might also work and if it works on GitHub Actions then I'll have arm64 builds for all future deployments.  Even if I can only test the x86_64 part.

> Didn't need to do anything with zlib - I guess MacOS has it included by default or something :S

If you've been using SCons or the GitHub releases then zlib was likely statically linked into libtcod.  The SCons script doesn't support linking zlib externally.

**Comment by SiennaSaito** [comment] 2020-12-31 08:25
I think there's a pretty good chance that we could make a universal binary - Apple seems to want us to be doing that so that the same blobs can run anywhere - I'll have to take a look and see what I can come up with - won't have access to an x86 laptop for a couple of days though!

Just tried running `scons develop_all MODE=RELEASE ARCH=arm64` and this is the inline asm error that I got:

```
g++ -o libtcod-1.16.0-alpha.15-arm64-RELEASE-macos/unittest -O3 -flto -arch arm64 -framework ApplicationServices -framework SDL2 -F./Frameworks/SDL2.framework/.. -rpath @loader_path/ -rpath @loader_path/../Frameworks -rpath /Library/Frameworks -rpath /System/Library/Frameworks libtcod-1.16.0-alpha.15-arm64-RELEASE-macos/tests/catch.o libtcod-1.16.0-alpha.15-arm64-RELEASE-macos/tests/unittest.o -Llibtcod-1.16.0-alpha.15-arm64-RELEASE-macos -L/Users/sienna/Dev/libtcod -ltcod
<inline asm>:1:6: error: invalid token in expression
        int $3
            ^
<inline asm>:1:6: error: invalid operand
        int $3
            ^
LLVM ERROR: Error parsing inline asm

clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [libtcod-1.16.0-alpha.15-arm64-RELEASE-macos/unittest] Error 1
scons: building terminated because of errors.
``` 

My interpretation is that its trying to compile unit tests and link it to SDL and other frameworks and is then running into something that it thinks is inline asm - I tried opening `unittests.cpp` and poking around there for a bit but I'm not seeing any `$3` anywhere - so part of me thinks this might be some kind of red herring. Not sure though - maybe the inline asm is coming from SDL?

**Comment by HexDecimal** [comment] 2020-12-31 08:53
I assumed x86 support was dropped.  I'd be good with just x86_64/arm64 since it feels like x86/x86_64/arm64 would be an uphill battle I wouldn't want to be part of.  I have to focus on what I can reproduce in GitHub Actions.  So I'll need to try to build arm64 in macos-11.0 or macos-10.15, which haven't been able to build x86 programs as far as I could tell.  The older architecture is only going to be less supported as time goes on.

> unittests.cpp

I assume it's an issue with the unit test library Catch2 and not with the tests themselves, SDL, or libtcod.  The problem is in `catch.hpp`.  I won't mind switching this library with another one.

The command `scons develop_samples` should build the samples without trying to make the unit tests.

**Comment by SiennaSaito** [comment] 2021-01-13 09:47
Oh yeah! `x86` was dropped - sorry, I've fallen into a bad habit of calling `x86_64` just `x86` :(
I can confirm that `scons develop_samples` works!

**Comment by SiennaSaito** [comment] 2021-01-13 09:54
Closed as we can now build libtcod for ARM64 on Darwin.

**Comment by HexDecimal** [comment] 2021-01-13 10:03
There are still no libtcod releases for arm64 until the GitHub workflows are updated to compile for it.

**Comment by SiennaSaito** [comment] 2021-01-13 10:12
Oh shit, yeah, this was about an arm64 release, not just compiling locally 😵
My bad. Reopening.

Let me know if there's a way I can help you out with GitHub workflows!

**Comment by HexDecimal** [comment] 2021-01-13 10:23
If you updated SCons to compile for `arm64` and `x86_64` simultaneously as mentioned above, verify that it compiles and works, then made a PR of that then I can try and update a workflow to make that universal build instead of being `x86_64` only.

I could try doing this on my own, but it's slower waiting for feedback from CI rather than working on the OS directly.

**Comment by SiennaSaito** [comment] 2021-01-13 11:28
I've raised a draft PR here - https://github.com/libtcod/libtcod/pull/86/files
Can't verify that it works yet but I'll do a test run ASAP and see if it works or if its just ignoring the additional architectures in the list.

**Comment by HexDecimal** [comment] 2021-01-25 06:33
Here's a universal 2 build from the current workflows:  [libtcod-1.16.0-alpha.15-universal2-macos.tar.gz](https://github.com/libtcod/libtcod/files/5864587/libtcod-1.16.0-alpha.15-universal2-macos.tar.gz)

As far as I can tell it works okay.  Now I'm able to add these whenever there's a new release.

I still have little clue on how to properly bundle the SDL framework with this, but that's a minor issue for now.

**Closed by HexDecimal** 2021-01-25 06:33 UTC
Labels: enhancement
