### ISSUE TITLE
Cannot compile (win, msys2, mingw)

### ISSUE THREAD

**Issue by Abalieno** [libtcod/libtcod#82] opened 2021-01-02 05:33 UTC
So I've been using an old version, circa 1.6, and everything's fine.

I've tried to download the latest version of libtcod to see how much I'd have to change to make it work, but it doesn't compile.

It looks like Scons comes by default with msys2, but you should update the instuction and say that the command "scons develop_all MODE=RELEASE" has to be executed under "/buildsys/scons". It's trivial but not immediate. Things used to be simpler using makefiles.

Anyway, this doesn't download SDL2, I I tried with:
pacman -Ss sdl

To search for a package available, and then:
pacman -S mingw64/mingw-w64-x86_64-SDL2

This is the version I got. There are others, like SDL2_image and SDL2_gfx. I only got the base one, and it seems to work.

It compiles up to a point, then throws this error:
G:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/msys2/mingw64/lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0xf6): undefined reference to `SDL_main'
collect2.exe: error: ld returned 1 exit status

I have absolutely no idea how to fix this, or why it happens. Not an expert.

**Comment by HexDecimal** [comment] 2021-01-02 12:13
I apologize.  The problem is that while the SCons builder is written and tested for Windows and even for MinGW on Windows, it wasn't tested on MSYS2 itself.  I could spend some time making this more compatible and also clear up the instructions.

Be sure to post more details and longer logs if you can.  I know what can cause `undefined reference to 'SDL_main'` but it's hard to tell what happened from what you've posted.  Unless `libSDL2main.a` really got linked by itself here which would definitely be the cause, because it must be linked with the source which has the `main` function.

**Comment by Abalieno** [comment] 2021-01-02 21:08
I've repeated the identical process today and for some unknown reason it produced a different result.

I simply downloaded the .zip from github and unpacked inside a directory, that's all.

This time it was able to produce samples_cpp.exe in the main dir, and it runs fine. But it still produces the same error on other files. This is the last part of the log:

g++ -o libtcod-1.16.0-alpha.15-x86_64-RELEASE/tests/catch.o -c -std=c++14 -Wnon-virtual-dtor -Woverloaded-virtual -Wuseless-cast -Wall -Wextra -Wpedantic -Wshadow=local -Wcast-align -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference -Wdouble-promotion -Wformat=2 -O3 -flto -fvisibility=hidden -m64 -Wno-deprecated-declarations -DNDEBUG -Dmain=SDL_main -Ilibtcod-1.16.0-alpha.15-x86_64-RELEASE/src/vendor/zlib -I/home/Abalieno/foe/libtcod-new/src/vendor/zlib -IG:/msys2/mingw64/include/SDL2 -Ilibtcod-1.16.0-alpha.15-x86_64-RELEASE/src -I/home/Abalieno/foe/libtcod-new/src /home/Abalieno/foe/libtcod-new/tests/catch.cpp
Install file: "libtcod-1.16.0-alpha.15-x86_64-RELEASE/libtcod.dll.a" as "/home/Abalieno/foe/libtcod-new/libtcod.dll.a"
Install file: "libtcod-1.16.0-alpha.15-x86_64-RELEASE/tcod.dll" as "/home/Abalieno/foe/libtcod-new/tcod.dll"
g++ -o libtcod-1.16.0-alpha.15-x86_64-RELEASE/samples_cpp.exe -O3 -flto -mwindows -m64 libtcod-1.16.0-alpha.15-x86_64-RELEASE/samples/samples_cpp.o -Llibtcod-1.16.0-alpha.15-x86_64-RELEASE -L/home/Abalieno/foe/libtcod-new -LG:/msys2/mingw64/lib -lmingw32 -lSDL2main -lSDL2 -lm -lSDL2 -lSDL2main -ltcod
Install file: "libtcod-1.16.0-alpha.15-x86_64-RELEASE/samples_cpp.exe" as "/home/Abalieno/foe/libtcod-new/samples_cpp.exe"
g++ -o libtcod-1.16.0-alpha.15-x86_64-RELEASE/navier.exe -O3 -flto -mwindows -m64 libtcod-1.16.0-alpha.15-x86_64-RELEASE/samples/navier/main.o -Llibtcod-1.16.0-alpha.15-x86_64-RELEASE -L/home/Abalieno/foe/libtcod-new -LG:/msys2/mingw64/lib -lmingw32 -lSDL2main -lSDL2 -lm -lSDL2 -lSDL2main -ltcod
g++ -o libtcod-1.16.0-alpha.15-x86_64-RELEASE/worldgen.exe -O3 -flto -mwindows -m64 libtcod-1.16.0-alpha.15-x86_64-RELEASE/samples/worldgen/main.o libtcod-1.16.0-alpha.15-x86_64-RELEASE/samples/worldgen/util_worldgen.o -Llibtcod-1.16.0-alpha.15-x86_64-RELEASE -L/home/Abalieno/foe/libtcod-new -LG:/msys2/mingw64/lib -lmingw32 -lSDL2main -lSDL2 -lm -lSDL2 -lSDL2main -ltcod
G:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/msys2/mingw64/lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0xf6): undefined reference to `SDL_main'
collect2.exe: error: ld returned 1 exit status
scons: *** [libtcod-1.16.0-alpha.15-x86_64-RELEASE/navier.exe] Error 1
G:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/msys2/mingw64/lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0xf6): undefined reference to `SDL_main'
collect2.exe: error: ld returned 1 exit status
scons: *** [libtcod-1.16.0-alpha.15-x86_64-RELEASE/worldgen.exe] Error 1
scons: building terminated because of errors.

So it seems to not be able to compile the other sample files, but the library itself should work. I'll try later to see if that's enough to compile my own program.

Another difference is that the program now requires these files:
libgcc_s_seh-1.dll
libstdc++-6.dll
libwinpthread-1.dll

These can be fine in the mingw64/bin directory, so it's not a problem, but the odd thing is that my own same program, compiled in the exact same environment but with the old libtcod only requires "libwinpthread-1.dll".

I think it used to require other files but I fixed it by using "-static" while compiling? In any case now it's different.

Another weird but minor thing is that after I compiled my program the first time (with the precompiled library "libtcod-1.16.0-alpha.15-x86_64-mingw.zip") it ran VERY SLOWLY. Where the previous version used 3% CPU on this old machine, the new .exe pushed cpu very high. It wasn't even running at 30 fps.

This was because it was still set to run at SDL1. I switched to GLSL and now it runs at about twice the speed of the original.

But performance doesn't seem the same. I compared the old samples_cpp, the old version produced 550 fps in SDL, and around 3500 on GLSL, the new one gives me 140 fps in SDL, 100 SDL2 and around 1200 in GLSL.

Still a big improvement in my case since I was stuck with SDL in the old version.

**Comment by Abalieno** [comment] 2021-01-03 02:27
I tried to compile in various ways but still failed.

The problem is than when I try to link the library to create the executable of my own program, it says it cannot find the library to link.

I've tried: -ltcod -libtcod -ltcod-mingw
None of these worked.

The problem is, with the already compiled version there's a libtcod.a 975kb file. In the one I compile instead I only have libtcod.dll.a much larger file 1.714kb.

In the old libtcod I have both a libtcod.a and a libtcod.dll.a

I've also tried:  scons build MODE=RELEASE ARCH=x86_64
This compiles to the end. But it produces nothing in the root directory of the library, and only a libtcod.dll.a hidden in the scons subdirectory.

So I don't know where to produce that correct .a that I can then use in the linker. And still have that undefined reference to SDL when compiling examples.

**Comment by Abalieno** [comment] 2021-01-03 02:39
And nevermind. Right after I wrote that I found the correct combitantion of flags that do produce a working library:
scons build MODE=RELEASE ARCH=x86_64 TOOLSET=mingw

I still had to go fish the libtcod.a in one scons working directory and move it somewhere usable.

Still cannot compile the samples.

**Comment by HexDecimal** [comment] 2021-01-03 02:58
> Another difference is that the program now requires these files:
libgcc_s_seh-1.dll
libstdc++-6.dll
libwinpthread-1.dll

This might be a regression.  I know I used to statically link these before.  I'll need to check the SCons script but I've been busy with other tasks lately.

>But performance doesn't seem the same. I compared the old samples_cpp, the old version produced 550 fps in SDL, and around 3500 on GLSL, the new one gives me 140 fps in SDL, 100 SDL2 and around 1200 in GLSL.

This is partially expected.  The new renderers in libtcod have some extra overhead from the ability to resize the window.  The older renderers would break if you tried to scale them.  The oldest SDL renderer was optimized for the CPU.  The new "SDL1" renderer runs on the CPU but isn't optimized for it since it's just the hardware accelerated version forced into software mode to be backward compatible with specific deprecated uses of libtcod.  The "SDL1" renderer will tank if you resized the window, while the others will be mostly unaffected.  While "SDL2" is slow it will work on any platform.  The new "GLSL" renderer was written for GLES which may have negatively affected its performance, but theoretically allows for web-assembly builds of libtcod with the renderer.

> The problem is that when I try to link the library to create the executable of my own program, it says it cannot find the library to link.

You'll need to tell the linker which directory has the shared library.  Posting the error itself including the command will help when figuring out what exactly went wrong.

**Comment by raspberrypisig** [comment] 2022-01-10 02:14
I just stumbled over requiring libgcc_s_seh-1.dll and libstdc++-6.dll while testing my custom setup with MSYS2. I now have to add to CMakeLists.txt
```
set(CMAKE_EXE_LINKER_FLAGS " -static")
target_link_libraries(roguelike-firststab PUBLIC -static-libgcc -static-libstdc++ libtcod::libtcod)
```

Using libtcod 1.19.0 via vcpkg

**Comment by HexDecimal** [comment] 2022-01-11 08:25
Looking back at this I think I identified the original problem.

>undefined reference to 'SDL_main'

This means `SDL2main` was linked but was missing the transformed `main` function from the main source.

Some samples worked, but others like `navier` did not.  The difference between these at the time was that some of them were including the SDL headers and defining `SDL_main` correctly while the other samples were behaving agnostic to SDL causing problems when linked with `SDL2main`.

This has no longer been the case for some time.  Right now all samples include SDL and all samples expect `SDL2main`.  I missed this at the time and when I eventually updated them I forgot to update this issue.  I'm closing this for now unless someone finds that the issue still exists.

> I just stumbled over requiring libgcc_s_seh-1.dll and libstdc++-6.dll while testing my custom setup with MSYS2.

This is normal GCC runtime stuff and not related to the original issue.  Everyone runs into this once because nobody ever warns anyone about their runtime requirements.  Maybe it would be worth it to append these flags when compiling with GCC+Windows.

**Closed by HexDecimal** 2022-01-11 08:25 UTC
Labels: bug
