### ISSUE TITLE
allow TCOD_sys_accumulate_console to target a specific area of the display

### ISSUE THREAD

**Issue by davemoore22** [libtcod/libtcod#65] opened 2020-05-25 22:17 UTC
The new SDL rendering functionality works wonderfully (thank you for that!), but I've noticed that the `TCOD_sys_accumulate_console` function overwrites the entire display when `SDL_RenderPresent` is called, even if the console specified is smaller than the main console.

Thus I have to do all my SDL manipulation after my libtcod manipulation. Not a problem in itself, but I'd like the ability to specify only a partial overwrite, so I can for example, produce something like the screen uploaded to a previous issue (#18) where this functionality was mentioned:

![image](https://user-images.githubusercontent.com/48893555/82845551-ef1efa80-9edc-11ea-95a7-0eebcf3bd26e.png)

The border/bottom text is the "background" layer, then I'd use SDL to render the view, and then I blit a small libtcod console displaying the "An Encounter" message. Currently if I do a second `TCOD_sys_accumulate_console` the "An Encounter" is scaled up to the entire screen.

If this is a matter of adding a overrides to the wrapper function `engine/display.cpp#TCOD_sys_accumulate_console` to translate libtcod coordinates into SDL coordinates for the `viewport` parameter used in `TCOD_sys_accumulate_console_`(and optionally providing an alpha value) would you be open to an appropriate pull request on this?

**Comment by HexDecimal** [comment] 2020-05-25 23:59
`TCOD_sys_accumulate_console` isn't future proof so it hasn't been a priority.  `TCOD_sdl2_render_texture` has taken over as the main way to handle this kind of thing:

Make your own SDL window so that you have full control, use `TCOD_sdl2_atlas_new` to prepare a libtcod tileset for rendering to it, call `TCOD_sdl2_render_texture` to render a libtcod console to an SDL texture, then blit that texture to your main renderer using whatever options you like.

`TCOD_sdl2_render_texture` isn't 100% stable, the API might break if I find a better way to handle the objects it wants to modify.

**Comment by HexDecimal** [comment] 2020-05-26 00:03
Those functions are documented in the header [here](https://github.com/libtcod/libtcod/blob/develop/src/libtcod/renderer_sdl2.h).

**Comment by davemoore22** [comment] 2020-05-26 00:06
Nice! This is pretty much what I wanted. Thank you!  I'll get playing with it over the next few days.

**Comment by HexDecimal** [comment] 2020-05-26 00:15
I think I'll mark this as a duplicate of #18. Any issues you have with `TCOD_sdl2_render_texture` should go there.

**Comment by HexDecimal** [comment] 2020-05-26 00:16
Duplicate of #18

**Closed** 2020-05-26 00:16 UTC
